name: Publish crate

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The reference to checkout
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.66.0

      - name: Publish acvm-backend-barretenberg
        run: |
          cargo publish --package acvm-backend-barretenberg --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.ACVM_BACKEND_BARRETENBERG_CRATES_IO_TOKEN }}
