name: Rust

on: [push, pull_request]

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  nix:
    name: Nix build & test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
          - os: macos-latest
            target: x86_64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cargo build
        run: |
          nix build -L .#checks.${{ matrix.target }}.cargo-check

      - name: Cargo clippy
        run: |
          nix build -L .#checks.${{ matrix.target }}.cargo-clippy

      - name: Cargo test
        run: |
          nix build -L .#checks.${{ matrix.target }}.cargo-test
