name: Rust

on: [push, pull_request]

jobs:
  check_n_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable, nightly]
    name: cargo check & test
    uses: noir-lang/.github/.github/workflows/rust-test.yml@main
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}

  clippy:
    name: cargo clippy
    uses: noir-lang/.github/.github/workflows/rust-clippy.yml@main

  format:
    name: cargo fmt
    uses: noir-lang/.github/.github/workflows/rust-format.yml@main
