name: Rust Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.66.0
      with:
        target: x86_64-unknown-linux-gnu
    
    - name: Download acvm_backend.wasm
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "AztecProtocol/barretenberg"
        tag: "barretenberg-v0.4.6"
        fileName: "acvm_backend.wasm.tar.gz"

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  test_mac:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.66.0
      with:
        target: x86_64-unknown-linux-gnu

    - name: Download acvm_backend.wasm
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "AztecProtocol/barretenberg"
        tag: "barretenberg-v0.4.6"
        fileName: "acvm_backend.wasm.tar.gz"

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
