name: Rust Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.67.0
        override: true
        target: x86_64-unknown-linux-gnu
    
    - name: Download acvm_backend.wasm
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "AztecProtocol/barretenberg"
        tag: "barretenberg-v0.4.6"
        fileName: "acvm_backend.wasm.tar.gz"

    - name: Run tests
      env:
        BARRETENBERG_ARCHIVE: "./acvm_backend.wasm.tar.gz"
      run: |
        cargo test


  test_mac:
    name: Test on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1.66.0
      with:
        profile: minimal
        override: true
        target: ${{ matrix.target }}

    - name: Download acvm_backend.wasm
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "AztecProtocol/barretenberg"
        tag: "barretenberg-v0.4.6"
        fileName: "acvm_backend.wasm.tar.gz"

    - name: Run tests
      env:
        BARRETENBERG_ARCHIVE: "./acvm_backend.wasm.tar.gz"
      run: |
        cargo test

