name: Rust Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.66.0
      with:
        target: x86_64-unknown-linux-gnu

    - name: Run tests
      env:
        RUST_TEST_THREADS: 1
      run: |
        cargo test

  test_mac:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@1.66.0
      with:
        target: ${{ matrix.target }}

    - name: Run tests
      env:
        RUST_TEST_THREADS: 1
      run: |
        cargo test
