name: Rust Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.67.0
        override: true
        target: x86_64-unknown-linux-gnu

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  test_mac:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.67.0
        override: true
        target: ${{ matrix.target }}

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
